import { Category } from "./types";

export const INTRO_QUESTIONS: Category = {
  id: "intro",
  name: "About You",
  icon: "👤",
  color: "#00D4FF",
  description: "Help us tailor your protocol",
  questions: [
    {
      id: "biological_sex",
      text: "What is your biological sex?",
      subtext: "This affects hormone recommendations and baseline physiology",
      type: "single",
      options: [
        { label: "Male", value: "male" },
        { label: "Female", value: "female" },
        { label: "Prefer not to say", value: "unspecified" },
      ],
    },
    {
      id: "age_range",
      text: "What is your age range?",
      subtext: "Metabolic and hormonal factors vary significantly by decade",
      type: "single",
      options: [
        { label: "18–25", value: "18-25" },
        { label: "26–35", value: "26-35" },
        { label: "36–45", value: "36-45" },
        { label: "46+", value: "46+" },
      ],
    },
    {
      id: "primary_goal",
      text: "What is your primary optimization goal?",
      subtext: "Select your top priority — we'll address everything, but weight this heavily",
      type: "single",
      options: [
        { label: "Facial appearance & aesthetics", value: "facial_appearance" },
        { label: "Hormonal balance & energy", value: "hormones_energy" },
        { label: "Body composition", value: "body_composition" },
        { label: "Overall health optimization", value: "overall" },
      ],
    },
  ],
};

export const CATEGORIES: Category[] = [
  {
    id: "facial_appearance",
    name: "Facial Appearance",
    icon: "🧬",
    color: "#00D4FF",
    description: "Skin, structure, and facial aesthetics",
    questions: [
      {
        id: "facial_bloat",
        text: "How often do you experience facial puffiness or bloating, especially in the morning?",
        subtext: "Facial puffiness often signals lymphatic, hormonal, or dietary issues",
        type: "single",
        options: [
          { label: "Rarely or never", value: "never" },
          { label: "1–2 times per week", value: "sometimes" },
          { label: "Most mornings", value: "often" },
          { label: "Every single morning", value: "always" },
        ],
      },
      {
        id: "skin_clarity",
        text: "How would you describe your skin clarity and texture?",
        type: "single",
        options: [
          { label: "Clear with minimal issues", value: "clear" },
          { label: "Occasional breakouts or dryness", value: "occasional" },
          { label: "Frequent acne or congestion", value: "frequent_acne" },
          { label: "Dull, uneven, or persistently problematic", value: "dull_uneven" },
        ],
      },
      {
        id: "jawline_definition",
        text: "How defined is your jawline and facial structure?",
        subtext: "Jaw definition is influenced by body fat, inflammation, chewing mechanics, and bone structure",
        type: "single",
        options: [
          { label: "Very defined — sharp and prominent", value: "very_defined" },
          { label: "Slightly soft with good structure", value: "slightly_soft" },
          { label: "Noticeably soft, fat around jaw/neck area", value: "soft" },
          { label: "Significant fat accumulation around face and neck", value: "significant_fat" },
        ],
      },
      {
        id: "facial_symmetry",
        text: "Do you notice asymmetry in your face?",
        subtext: "Asymmetry can be structural, postural, or functional in origin",
        type: "single",
        options: [
          { label: "No noticeable asymmetry", value: "none" },
          { label: "Mild — doesn't bother me", value: "mild" },
          { label: "Moderate — I notice it often in photos", value: "moderate" },
          { label: "Significant asymmetry", value: "significant" },
        ],
      },
      {
        id: "teeth_grinding",
        text: "Do you grind your teeth or chronically clench your jaw?",
        subtext: "Bruxism affects masseter hypertrophy, TMJ, and facial width",
        type: "single",
        showIf: { questionId: "jawline_definition", values: ["slightly_soft", "soft", "significant_fat"] },
        options: [
          { label: "Never", value: "never" },
          { label: "Occasionally under stress", value: "occasionally" },
          { label: "Often — I catch myself clenching", value: "often" },
          { label: "Yes — I've been told I grind at night", value: "night_grinding" },
        ],
      },
    ],
  },
  {
    id: "hormones",
    name: "Hormones",
    icon: "⚡",
    color: "#F5A623",
    description: "Hormonal balance and endocrine health",
    questions: [
      {
        id: "energy_levels",
        text: "How would you rate your energy levels throughout the day?",
        subtext: "Energy patterns are one of the most reliable hormonal indicators",
        type: "single",
        options: [
          { label: "Consistently high and stable", value: "high_stable" },
          { label: "Good in the morning, afternoon crash", value: "afternoon_crash" },
          { label: "Frequently fatigued regardless of sleep", value: "frequently_fatigued" },
          { label: "Chronically exhausted — always running on empty", value: "chronically_exhausted" },
        ],
      },
      {
        id: "hormonal_symptoms",
        text: "Which of the following do you currently experience?",
        subtext: "Select all that apply",
        type: "multi",
        options: [
          { label: "Brain fog or difficulty concentrating", value: "brain_fog" },
          { label: "Mood swings or irritability", value: "mood_swings" },
          { label: "Low libido or reduced drive", value: "low_libido" },
          { label: "Difficulty building or maintaining muscle", value: "muscle_difficulty" },
          { label: "None of the above", value: "none" },
        ],
      },
      {
        id: "body_composition_change",
        text: "Have you noticed unexplained body composition changes?",
        subtext: "Changes without major lifestyle shifts often indicate hormonal shifts",
        type: "single",
        options: [
          { label: "No significant changes", value: "stable" },
          { label: "Gaining fat, especially around the midsection", value: "fat_gain" },
          { label: "Losing muscle despite exercising regularly", value: "muscle_loss" },
          { label: "Both gaining fat and losing muscle simultaneously", value: "both" },
        ],
      },
      {
        id: "mental_clarity",
        text: "How would you describe your mental clarity and cognitive sharpness?",
        type: "single",
        options: [
          { label: "Sharp and consistent throughout the day", value: "sharp" },
          { label: "Occasional fog, mostly manageable", value: "occasional_fog" },
          { label: "Frequent brain fog — noticeable every day", value: "frequent_fog" },
          { label: "Severely impaired — affects work and relationships", value: "severe" },
        ],
      },
    ],
  },
  {
    id: "sleep_recovery",
    name: "Sleep & Recovery",
    icon: "🌙",
    color: "#7C3AED",
    description: "Sleep quality and cellular repair",
    questions: [
      {
        id: "sleep_duration",
        text: "How many hours of sleep do you typically get per night?",
        subtext: "Sleep duration directly affects growth hormone, cortisol, and testosterone cycles",
        type: "single",
        options: [
          { label: "7–9 hours (optimal range)", value: "optimal" },
          { label: "6–7 hours (slightly short)", value: "slightly_short" },
          { label: "Less than 6 hours", value: "insufficient" },
          { label: "More than 9 hours but still tired", value: "oversleeping" },
        ],
      },
      {
        id: "sleep_quality",
        text: "How do you feel when you wake up in the morning?",
        type: "single",
        options: [
          { label: "Refreshed, energized, and alert", value: "refreshed" },
          { label: "Slightly groggy but functional within 30 min", value: "slightly_groggy" },
          { label: "Usually tired regardless of hours slept", value: "tired" },
          { label: "Exhausted — like I barely slept at all", value: "exhausted" },
        ],
      },
      {
        id: "sleep_issues",
        text: "Do you experience difficulty falling or staying asleep?",
        type: "single",
        options: [
          { label: "Fall asleep easily and stay asleep all night", value: "no_issues" },
          { label: "Takes 15–30 minutes to fall asleep", value: "slow_onset" },
          { label: "Wake up multiple times during the night", value: "wake_up" },
          { label: "Struggle both falling asleep AND staying asleep", value: "both_issues" },
        ],
      },
      {
        id: "sleep_schedule",
        text: "What does your sleep schedule typically look like?",
        subtext: "Circadian alignment has major effects on hormonal timing",
        type: "single",
        options: [
          { label: "Consistent — asleep before 11pm, wake before 7am", value: "consistent_early" },
          { label: "Mostly 11pm–midnight range, somewhat consistent", value: "consistent_late" },
          { label: "After midnight most nights", value: "late" },
          { label: "Highly irregular — changes day to day", value: "irregular" },
        ],
      },
    ],
  },
  {
    id: "nutrition_gut",
    name: "Nutrition & Gut Health",
    icon: "🌿",
    color: "#10B981",
    description: "Diet, digestion, and the gut-skin axis",
    questions: [
      {
        id: "bloating_frequency",
        text: "How often do you experience bloating or digestive discomfort?",
        subtext: "Gut inflammation directly affects skin clarity, facial bloating, and systemic inflammation",
        type: "single",
        options: [
          { label: "Rarely or never", value: "never" },
          { label: "After certain foods — I know my triggers", value: "food_specific" },
          { label: "Most days regardless of what I eat", value: "most_days" },
          { label: "Chronic and constant throughout the day", value: "chronic" },
        ],
      },
      {
        id: "diet_quality",
        text: "How would you describe your typical diet?",
        type: "single",
        options: [
          { label: "Primarily whole foods, mostly home-cooked", value: "whole_foods" },
          { label: "Mix of whole foods and occasional processed food", value: "mixed" },
          { label: "Mostly processed, fast food, or restaurant meals", value: "mostly_processed" },
          { label: "Highly restrictive or specialized diet", value: "restrictive" },
        ],
      },
      {
        id: "hydration",
        text: "How would you rate your daily hydration?",
        subtext: "Chronic mild dehydration causes facial dullness, cognitive impairment, and poor skin elasticity",
        type: "single",
        options: [
          { label: "Excellent — drink 2.5+ liters of water daily", value: "excellent" },
          { label: "Good — 1.5–2.5 liters most days", value: "good" },
          { label: "Poor — less than 1.5 liters most days", value: "poor" },
          { label: "Mostly drink coffee, soda, or other beverages", value: "mostly_other" },
        ],
      },
      {
        id: "food_sensitivities",
        text: "Do you have known food sensitivities or digestive conditions?",
        type: "multi",
        options: [
          { label: "Dairy sensitivity or lactose intolerance", value: "dairy" },
          { label: "Gluten sensitivity or celiac disease", value: "gluten" },
          { label: "Multiple food sensitivities", value: "multiple" },
          { label: "Diagnosed gut condition (IBS, SIBO, etc.)", value: "diagnosed" },
          { label: "None known", value: "none" },
        ],
      },
    ],
  },
  {
    id: "posture_mechanics",
    name: "Posture & Body Mechanics",
    icon: "🦴",
    color: "#F59E0B",
    description: "Structural alignment and movement patterns",
    questions: [
      {
        id: "posture_assessment",
        text: "How would you describe your posture?",
        subtext: "Posture affects facial structure, breathing mechanics, and hormonal expression",
        type: "single",
        options: [
          { label: "Generally upright and balanced", value: "good" },
          { label: "Slight forward lean — I notice it sometimes", value: "slight_forward" },
          { label: "Forward head posture and rounded shoulders", value: "forward_head" },
          { label: "Significant spinal issues or chronic pain", value: "significant_issues" },
        ],
      },
      {
        id: "sitting_hours",
        text: "How many hours per day do you spend sitting?",
        subtext: "Prolonged sitting compresses the spine, affects lymph flow, and alters hormonal output",
        type: "single",
        options: [
          { label: "Less than 4 hours", value: "low" },
          { label: "4–6 hours", value: "moderate" },
          { label: "6–8 hours", value: "high" },
          { label: "More than 8 hours", value: "very_high" },
        ],
      },
      {
        id: "pain_frequency",
        text: "Do you experience neck, back, or shoulder pain?",
        type: "single",
        options: [
          { label: "No pain whatsoever", value: "none" },
          { label: "Occasional mild discomfort after long days", value: "occasional" },
          { label: "Regular pain that affects my daily life", value: "regular" },
          { label: "Chronic pain or diagnosed spinal condition", value: "chronic" },
        ],
      },
      {
        id: "exercise_frequency",
        text: "How often do you engage in structured physical exercise?",
        subtext: "Exercise frequency affects muscle tone, hormonal baseline, and lymphatic drainage",
        type: "single",
        options: [
          { label: "5+ times per week", value: "high" },
          { label: "3–4 times per week", value: "moderate" },
          { label: "1–2 times per week", value: "low" },
          { label: "Rarely or never", value: "never" },
        ],
      },
    ],
  },
  {
    id: "stress_nervous_system",
    name: "Stress & Nervous System",
    icon: "🧠",
    color: "#EF4444",
    description: "HPA axis, cortisol, and nervous system regulation",
    questions: [
      {
        id: "stress_level",
        text: "How would you rate your average daily stress level?",
        subtext: "Chronic stress dysregulates cortisol, accelerates aging, and worsens every other metric",
        type: "single",
        options: [
          { label: "Low — I manage stress well and feel grounded", value: "low" },
          { label: "Moderate — manageable most days", value: "moderate" },
          { label: "High — often overwhelmed or anxious", value: "high" },
          { label: "Severe — significantly affecting my health and functioning", value: "severe" },
        ],
      },
      {
        id: "stress_symptoms",
        text: "Which of these do you experience? Select all that apply.",
        type: "multi",
        options: [
          { label: "Racing thoughts or difficulty unwinding", value: "racing_thoughts" },
          { label: "Frequent tension headaches", value: "headaches" },
          { label: "Digestive issues that worsen under stress", value: "stress_digestion" },
          { label: "Difficulty recovering emotionally from setbacks", value: "slow_recovery" },
          { label: "None of these", value: "none" },
        ],
      },
      {
        id: "stress_management",
        text: "What stress management practices do you currently use consistently?",
        type: "multi",
        options: [
          { label: "Daily meditation or breathwork", value: "meditation" },
          { label: "Regular exercise for stress relief", value: "exercise" },
          { label: "Journaling or cognitive tools", value: "journaling" },
          { label: "Social connection and community", value: "social" },
          { label: "None consistently", value: "none" },
        ],
      },
      {
        id: "stress_appearance_impact",
        text: "How does stress visibly manifest in your body or appearance?",
        type: "single",
        options: [
          { label: "Minimal — stress doesn't seem to affect how I look", value: "minimal" },
          { label: "Occasional breakouts or puffiness during stressful periods", value: "occasional" },
          { label: "Noticeable changes in skin, weight, and energy", value: "noticeable" },
          { label: "Significant physical manifestations — visible aging, major flares", value: "significant" },
        ],
      },
    ],
  },
];

export const ALL_CATEGORIES = [INTRO_QUESTIONS, ...CATEGORIES];
